# Generated by Django 5.1.4 on 2025-03-19 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_enduser_staff_alter_user_options_user_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(blank=True, max_length=200)),
                ('max_mentee_capacity', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='MenteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_interests', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='enduserprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffuserprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='EndUser',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.CreateModel(
            name='CaseManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_custom_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('MENTEE', 'Mentee'), ('CASE_MANAGER', 'Case Manager')], default='MENTEE', max_length=50, verbose_name='User Type'),
        ),
        migrations.AddField(
            model_name='casemanagerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='case_manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'CASE_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_mentees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menteeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EndUserProfile',
        ),
        migrations.DeleteModel(
            name='StaffUserProfile',
        ),
    ]
